/**
 * Side-effect imports — each handler file calls `registerPhaseEffect`
 * at module-load time. Import this file once from the dispatcher so the
 * registry is populated before `applyModePhaseEffects` is called.
 *
 * New mechanic? Add a file under this directory, then one line here.
 */
import "./absorbLastHandToBoard";
import "./adoptBlackScoring";
import "./adoptRedScoring";
import "./armRankInvert";
import "./bestCardClockwise";
import "./breakBoardPairs";
import "./cipherRanksWithRiver";
import "./coinflipScoreRule";
import "./convergeSevensToAces";
import "./counterfeitInversion";
import "./crossHandCardSwap";
import "./draftFromFlop";
import "./duplicateFlopPhase";
import "./executeRankInvert";
import "./faceCardsToAces";
import "./faceCardsToTwos";
import "./festivalBoostFirstCommunity";
import "./firstCommunityAbsorbsSecondSuit";
import "./flopOneAtATime";
import "./glitchCopyNeighbor";
import "./hostageRankBecomesWild";
import "./incrementAllHoleRanks";
import "./incrementAllRanks";
import "./incrementFirstCommunityRank";
import "./incrementFirstHolePerHand";
import "./invertAllRanks";
import "./invertScoringNow";
import "./lockMajorityColor";
import "./lockTopHalfAtFlop";
import "./markFirstBoard";
import "./markOneBoardWild";
import "./mirrorCommunity";
import "./mixHolesWithBurn";
import "./noopMetaEffects";
import "./optedTierPenalty";
import "./randomReplaceVisibleCommunity";
import "./reassignAllSuits";
import "./removeAdjacentToRiver";
import "./removeFaceCards";
import "./removeFirstHolePerHand";
import "./removeHighestRankInPlay";
import "./removeLastCommunity";
import "./removeOneHolePerHand";
import "./removeSevens";
import "./rerollFlopAtTurn";
import "./reverseCommunity";
import "./reverseTableAndBoard";
import "./revertBoardToFlop";
import "./revertToFlopBriefly";
import "./rewindToTurnAfterReveal";
import "./riverOverwritesSuit";
import "./rotateAllCardPositions";
import "./rotateFirstHoleCardsClockwise";
import "./rotateHoleCardsClockwise";
import "./rotateHoleRanksAcrossHands";
import "./schismDeckHighOnly";
import "./scrambleCommunitySuits";
import "./shuffleAllHoleCards";
import "./shuffleCommunity";
import "./shuffleHandAssignment";
import "./singularityAverageFirstTwoHoles";
import "./splitHandsAtReveal";
import "./spreadPlagueToFirstCard";
import "./staticFlickerFirstCards";
import "./stormSurge";
import "./stripBoardSuits";
import "./swapFirstCardsFirstTwoHands";
import "./swapFirstHoleWithFirstCommunity";
import "./tarotRankShift";
import "./tricksterSwapRight";
import "./upgradeHighestHole";
import "./zeroHighRanks";
